package com.insuretrack.mapper;

import com.insuretrack.dto.CustomerRequestDTO;
import com.insuretrack.dto.CustomerResponseDTO;
import com.insuretrack.entity.Customer;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring", uses = {BeneficiaryMapper.class, InsuredObjectMapper.class})
public interface CustomerModuleMapper {

    // Map DTO to Entity (Used during Registration)
    @Mapping(target = "customerID", ignore = true) // Generated by DB
    @Mapping(target = "userID", ignore = true)     // Set manually in Service
    @Mapping(target = "beneficiaries", source = "beneficiaries")
    @Mapping(target = "insuredObjects", source = "insuredObjects")
    Customer toEntity(CustomerRequestDTO dto);

    // Map Entity to Response
    @Mapping(target = "email", ignore = true)      // Set manually in Service
    @Mapping(target = "phone", ignore = true)      // Set manually in Service
    @Mapping(target = "userID", source = "userID") // Maps the Long userID from Customer
    CustomerResponseDTO toResponse(Customer customer);
}